dependencies = {
  "curl.se"                          = "*"
  "facebook.com/zstd"                = "*"
  "github.com/besser82/libxcrypt"    = "*"
  "github.com/util-linux/util-linux" = "*"
  "gnu.org/libidn2"                  = "*"
  "gnutls.org"                       = "*"
  "google.com/fullycapable"          = "*"
  "libexpat.github.io"               = "*"
  "lz4.org"                          = "*"
  "openssl.org"                      = "^3"
  "pcre.org/v2"                      = "*"
  "sourceware.org/bzip2"             = "*"
  "tukaani.org/xz"                   = "*"
}
